name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Analyze code with pylint
      run: |
        pylint $(git ls-files '*.py') || true  # Ensures that the workflow doesn't fail on pylint warnings
      continue-on-error: true  # Optionally, allows the workflow to continue even if pylint fails

    - name: Upload pylint report
      if: failure()  # Only upload report if pylint fails
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint-report.txt
